// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using entityFramework;

#nullable disable

namespace entityFramework.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20241221022915_ArregloDeLasColumnas")]
    partial class ArregloDeLasColumnas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("entityFramework.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoriaDescipcion")
                        .HasColumnType("text");

                    b.Property<string>("CategoriaNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PesoCategoria")
                        .HasColumnType("integer");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("947f788f-c28b-4267-8b6c-f190fb513ca7"),
                            CategoriaNombre = "Actividades Pendientes",
                            PesoCategoria = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("947f788f-c28b-4267-8b6c-f190fb513c02"),
                            CategoriaNombre = "Actividades Personales",
                            PesoCategoria = 50
                        });
                });

            modelBuilder.Entity("entityFramework.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TareaDescripcion")
                        .HasColumnType("text");

                    b.Property<bool>("TareaGosu")
                        .HasColumnType("boolean");

                    b.Property<int>("TareaPrioridad")
                        .HasColumnType("integer");

                    b.Property<string>("TareaTitulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TareaId");

                    b.HasAlternateKey("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("947f788f-c28b-4267-8b6c-f190fb513c10"),
                            CategoriaId = new Guid("947f788f-c28b-4267-8b6c-f190fb513ca7"),
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TareaGosu = false,
                            TareaPrioridad = 1,
                            TareaTitulo = "Pago de la U"
                        },
                        new
                        {
                            TareaId = new Guid("947f788f-c28b-4267-8b6c-f190fb513c11"),
                            CategoriaId = new Guid("947f788f-c28b-4267-8b6c-f190fb513c02"),
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TareaGosu = false,
                            TareaPrioridad = 2,
                            TareaTitulo = "Pago del cuarto"
                        });
                });

            modelBuilder.Entity("entityFramework.Models.Tarea", b =>
                {
                    b.HasOne("entityFramework.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("entityFramework.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
